repos:
      - repo: local
        hooks:
              - id: checkstyle
                name: checkstyle
                description: Check style black flake8 clang
                entry: ./ci/checks/style.sh
                language: system
                types: [file]

default_language_version:
      python: python3
